### ISSUE TITLE
https implementation broken

### ISSUE THREAD

**Issue by aamerik** [kcl-nmssys/puppet-influxdb#1]
hi, i noticed a couple of issues when https is enabled:

1) user/database/grant creation fails over https://localhost because ssl certificate CN name does not match 'localhost' in a real world use-case.  a flag should be added to support insecure ssl via -unsafeSsl

2) module should not enforce https certificate and key contents if manage_ssl is false.

Thank you!

**Comment by xandm** [comment]
1. Should be fixed by new version of module available on Puppet Forge.
2. Not sure what you mean, isn't this already the case?

**Comment by xandm** [comment]
I believe second issue is fixed by https://github.com/kcl-nmssys/puppet-influxdb/pull/6
